name: Generate Sitemap

on:
  schedule:
    - cron: "0 0 * * *"   # otomatis setiap hari jam 00:00 UTC
  workflow_dispatch:       # bisa dijalankan manual dari tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate sitemap
        run: python generate_sitemap.py

      - name: Commit & Push sitemap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Auto update sitemap" || echo "No changes"
          git push
